"""Alembic migrations package for the VISION schema.

Contains the Alembic environment (env.py) and generated revision scripts under
``versions/``. The initial revision is autogenerated later against
``Base.metadata``; this scaffold only wires the environment.
"""
